trigger: none

resources:
  repositories:
  - repository: templates
    type: git
    name: Meridian/meridian-pipeline-templates
    ref: refs/tags/v1.0.0

variables:
- name: Meridian.Component
  value: platform-libraries

extends:
  template: pipelines/extends/library.yml@templates
  parameters:
    name: platform-libraries
    packProjects: src/**/*.csproj
    deploy: false
